config/urls.py
from django.conf                    import settings
from django.views                   import defaults as default_views
from django.contrib                 import admin
from django.conf.urls               import include, url
from django.views.i18n              import javascript_catalog
from django.conf.urls.static        import static
from django.contrib.flatpages.views import flatpage

from kleemablech.views import faq_view
from kleemablech.views import home_view
from kleemablech.views import share_view
from kleemablech.views import history_view
from kleemablech.views import contact_view
from kleemablech.views import transfert_view
from kleemablech.views import dashboard_view
from kleemablech.views import parameters_view
from kleemablech.views import sponsorship_view
from kleemablech.views import step2_signup_view
from kleemablech.views import video_player_view
from kleemablech.views import video_timeout_view
from kleemablech.views import phone_numbers_view
from kleemablech.views import video_counter_view
from kleemablech.views import picture_upload_view
from kleemablech.views import check_phone_number_view
from kleemablech.views import news_letter_emails_view
from kleemablech.views import video_felicitation_view
from kleemablech.views import video_informations_view
from kleemablech.views import monthly_wins_stats_view
from kleemablech.views import monthly_views_stats_view
from kleemablech.views import monthly_refills_stats_view
from kleemablech.views import twitter_followers_count_view
from kleemablech.views import facebook_followers_count_view

js_info_dict = {
    'packages': ('kleemablech.front',),
}

urlpatterns = [
    # User signup
    url(r'^signup_step2/$', step2_signup_view, name='signup_step2'),

    # 3rd parties urls
    url(r'^admin/'      , include(admin.site.urls                            )),
    url(r'^pages/'      , include('django.contrib.flatpages.urls'            )),
    url(r'^accounts/'   , include('allauth.urls'                             )),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),

    # Profile tabs
    url(r'^history/$'   , history_view   , name='history'   ),
    url(r'^dashboard/$' , dashboard_view , name='dashboard' ),
    url(r'^transfert/$' , transfert_view , name='transfert' ),
    url(r'^parameters/$', parameters_view, name='parameters'),

    # Web services
    url(r'^phone_numbers/$'                 , phone_numbers_view           , name='phone_numbers'           ),
    url(r'^picture_upload/$'                , picture_upload_view          , name='picture_upload'          ),
    url(r'^news_letter_emails/$'            , news_letter_emails_view      , name='news_letter_emails'      ),
    url(r'^check_phone_number/(?P<phone>)'  , check_phone_number_view      , name='check_phone_number'      ),
    url(r'^twitter_followers_count_view/$'  , twitter_followers_count_view , name='twitter_followers_count' ),
    url(r'^facebook_followers_count_view/$' , facebook_followers_count_view, name='facebook_followers_count'),

    # Main pages
    url(r'^$'            , home_view       , name="home"       ),
    url(r'^faq/$'        , faq_view        , name="faq"        ),
    url(r'^share/$'      , share_view      , name="share"      ),
    url(r'^contact/$'    , contact_view    , name="contact"    ),
    url(r'^sponsorship/$', sponsorship_view, name="sponsorship"),

    # Flat pages
    url(r'^privacy_policy/$'      , flatpage, {'url': '/privacy_policy/'      }, name='privacy_policy'      ),
    url(r'^terms_and_conditions/$', flatpage, {'url': '/terms_and_conditions/'}, name='terms_and_conditions'),

    # Videos
    url(r'^video_timeout/$'                       , video_timeout_view     , name='video_timeout'     ),
    url(r'^video_player/(?P<video>[0-9]+)/$'      , video_player_view      , name='video_player'      ),
    url(r'^video_counter/(?P<video>[0-9]+)/$'     , video_counter_view     , name='video_counter'     ),
    url(r'^video_felicitation/(?P<key>.+)/$'      , video_felicitation_view, name='video_felicitation'),
    url(r'^video_informations/(?P<video>[0-9]+)/$', video_informations_view, name='video_informations'),

    # Statistics
    url(r'^stats/win/monthly/$'   , monthly_wins_stats_view   , name='monthly_wins_stats'   ),
    url(r'^stats/view/monthly/$'  , monthly_views_stats_view  , name='monthly_views_stats'  ),
    url(r'^stats/refill/monthly/$', monthly_refills_stats_view, name='monthly_refills_stats'),

    # Javascript localization
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^500/$', default_views.server_error                                                           ),
        url(r'^400/$', default_views.bad_request      , kwargs={'exception': Exception("Bad Request!"     )}),
        url(r'^404/$', default_views.page_not_found   , kwargs={'exception': Exception("Page not Found"   )}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
    ]

kleemablech/models/campaign.py
from decimal                import Decimal
from datetime               import datetime
from easy_thumbnails.files  import get_thumbnailer
from dateutil.relativedelta import relativedelta

from django.db.models           import Q
from django.db.models           import Sum
from django.db.models           import Count
from django.db.models           import Model
from django.db.models           import CharField
from django.db.models           import ImageField
from django.db.models           import ForeignKey
from django.db.models           import FileField
from django.db.models           import PositiveIntegerField
from django.db.models           import BooleanField
from django.db.models           import DateField
from django.db.models           import DecimalField
from django.utils.html          import mark_safe
from django.core.exceptions     import ValidationError
from django.utils.translation   import gettext_lazy as _
from django.db.models.functions import Coalesce

from kleemablech.models.win     import CampaignWin
from kleemablech.models.user    import User
from kleemablech.models.refill  import Refill
from kleemablech.utils.strings  import month_labels
from kleemablech.models.choices import VIDEO_POSITION_CHOICES


class Campaign(Model):
    draw                      = BooleanField        (_('draw'                     ), default=False                                )
    title                     = CharField           (_('title'                    ), max_length=255                               )
    image                     = ImageField          (_('image'                    ), upload_to='campaigns/image'                  )
    video                     = FileField           (_('video'                    ), upload_to='campaigns/video'                  )
    brand                     = CharField           (_('brand'                    ), max_length=255                               )
    active                    = BooleanField        (_('active'                   ), default=True                                 )
    duration                  = PositiveIntegerField(_('duration'                 )                                               )
    position                  = CharField           (_('position'                 ), max_length=50, choices=VIDEO_POSITION_CHOICES)
    start_date                = DateField           (_('start date'               )                                               )
    draw_amount               = DecimalField        (_('draw amount'              ), decimal_places=3, max_digits=9               )
    total_amount              = PositiveIntegerField(_('total amount'             )                                               )
    total_winners             = PositiveIntegerField(_('total winners'            )                                               )
    unique_visitors           = PositiveIntegerField(_('unique visitors'          )                                               )
    direct_win_amount         = DecimalField        (_('direct win amount'        ), decimal_places=3, max_digits=9               )
    cumulative_win_amount     = DecimalField        (_('cumulative win amount'    ), decimal_places=3, max_digits=9               )
    direct_win_percentage     = PositiveIntegerField(_('direct win percentage'    )                                               )
    campaign_end_draw_amount  = DecimalField        (_('campaign end draw amount' ), decimal_places=3, max_digits=9               )
    cumulative_win_percentage = PositiveIntegerField(_('cumulative win percentage')                                               )

    class Meta:
        app_label           = 'kleemablech'
        verbose_name        = _('Campaign' )
        verbose_name_plural = _('Campaigns')

    def __str__(self):
        return self.title

    def clean(self):
        if self.direct_win_percentage + self.cumulative_win_percentage != 100:
            raise ValidationError(_('The sum of direct and cumultative win percentage must equal 100'))

    @staticmethod
    def total_amount_sum():
        return int(Campaign.objects.filter(active=True).aggregate(
            amount=Coalesce(Sum('total_amount'), 0))['amount'])

    @staticmethod
    def total_winable_amount():
        return Campaign.total_amount_sum() - int(
            CampaignWin.objects.filter(verified=True).aggregate(
                amount=Coalesce(Sum('amount'), 0))['amount'])

    @staticmethod
    def total_winable_percentage():
        total_amount_sum     = Decimal(Campaign.total_amount_sum    ())
        total_winable_amount = Decimal(Campaign.total_winable_amount())

        if total_amount_sum != 0 and total_winable_amount > total_amount_sum:
            return int((total_winable_amount / total_amount_sum) * 100)
        return 0

    def winable_percentage(self):
        amount = self.total_amount - CampaignWin.total_campaign_wins(self)
        if self.total_amount != 0 and amount > 0:
            return int(amount / self.total_amount * 100)
        return 0

    def total_refills(self):
        return Refill.campaign_total_refill(self)

    def total_views(self):
        return CampaignView.total_campaign_views(self)

    def winners_total(self):
        return CampaignWin.total_campaign_winners(self)

    def image_img(self):
        if self.image:
            return mark_safe('<img src="{}" />'.format(
                get_thumbnailer(self.image).get_thumbnail(
                    {'size': (200, 200), 'crop': True}).url))
        else:
            return _('no image')
    image_img.short_description = 'Thumb'

    def video_video(self):
        if self.video:
            return mark_safe(
                '<video height="250" controls><source src="{}"></source></video>'.format(
                    self.video.url))
        else:
            return _('no video')
    video_video.short_description = 'Video media'


class CampaignView(Model):
    date = DateField(_('date'), auto_now_add=True)

    user     = ForeignKey(User    , verbose_name=_('user'    ))
    campaign = ForeignKey(Campaign, verbose_name=_('campaign'))

    class Meta:
        app_label           = 'kleemablech'
        verbose_name        = _('Campaign View' )
        verbose_name_plural = _('Campaign Views')

    def __str__(self):
        return u'{} - {} - {}'.format(self.date, self.user, self.campaign)

    @staticmethod
    def monthly_user_stats(user):
        seven_months = datetime.today() + relativedelta(day=1, months=-6)
        views = CampaignView.objects.filter(
            Q(user=user                   ) &
            Q(date__gt=seven_months.date())
        ).extra(select={
            'year' : 'EXTRACT(year  FROM date)',
            'month': 'EXTRACT(month FROM date)',
        }).values('year', 'month').annotate(num_views=Count('date')).order_by('year', 'month')

        temp   = {view['month']: view for view in views}
        labels = []
        values = []

        for x in range(0, 7):
            month = (seven_months + relativedelta(months=+x)).month
            labels.append(month_labels[month - 1])
            if month in temp:
                values.append(temp[month]['num_views'])
            else:
                values.append(0)
        return {'labels': labels, 'values': values}

    @staticmethod
    def user_total_campaigns_views(user):
        return CampaignView.objects.filter(user=user).values('campaign').distinct().count()

    @staticmethod
    def total_campaign_views(campaign):
        return CampaignView.objects.filter(campaign=campaign).aggregate(
            total_views=Coalesce(Count('id'), 0))['total_views']

kleemablech/models/news_letter.py
from django.db.models         import Model
from django.db.models         import EmailField
from django.db.models         import BooleanField
from django.utils.translation import ugettext_lazy as _


class NewsletterEmails(Model):
    email  = EmailField  (_('email'), max_length=100, unique=True)
    active = BooleanField(_('active'), default=True)

    class Meta:
        app_label           = 'kleemablech'
        verbose_name        = _('News letter email' )
        verbose_name_plural = _('News letter emails')

    def __str__(self):
        return self.email

kleemablech/models/phone_number.py
from django.db.models         import Model
from django.db.models         import CharField
from django.db.models         import ForeignKey
from django.utils.translation import ugettext_lazy as _

from kleemablech.models.user import User


class PhoneNumber(Model):
    number = CharField (_('number'), max_length=50)

    user = ForeignKey(User, verbose_name=_('user'))

    class Meta:
        app_label           = 'kleemablech'
        verbose_name        = _('Phone number' )
        unique_together     = (("user", "number"),)
        verbose_name_plural = _('Phone numbers')

    @property
    def operator(self):
        return {
            '5': u'orange',
            '2': u'ooredoo',
            '9': u'tunisie_telecom',
            '4': u'tunisie_telecom',
        }.get(self.number[0], u'unknown')

    def __str__(self):
        return self.number

kleemablech/admin/campaign/forms.py
from django.forms import ModelForm
from suit.widgets import SuitDateWidget

from kleemablech.models import Campaign


class CampaignForm(ModelForm):
    class Meta:
        model   = Campaign
        fields  = '__all__'
        widgets = {
            'start_date': SuitDateWidget,
        }

kleemablech/admin/campaign_view/forms.py
from django.forms import ModelForm

from kleemablech.models.campaign import CampaignView


class CampaignViewForm(ModelForm):
    class Meta:
        model  = CampaignView
        fields = '__all__'

kleemablech/admin/featured_topic/forms.py
from django.forms import ModelForm

from kleemablech.models import FeaturedTopic


class FeaturedTopicForm(ModelForm):
    class Meta:
        model   = FeaturedTopic
        fields  = '__all__'

kleemablech/admin/flatpage/forms.py
from suit_redactor.widgets          import RedactorWidget
from django.contrib.flatpages.admin import FlatpageForm


class FlatpageForm(FlatpageForm):
    class Meta:
        widgets = {
            'content': RedactorWidget(editor_options={'lang': 'fr', 'minHeight': 300}),
        }

kleemablech/admin/news_letter/forms.py
from django.forms import ModelForm

from kleemablech.models import NewsletterEmails


class NewsletterEmailsForm(ModelForm):
    class Meta:
        model  = NewsletterEmails
        fields = '__all__'

kleemablech/admin/operator/forms.py
from django.forms import ModelForm

from kleemablech.models import Operator


class OperatorForm(ModelForm):
    class Meta:
        model   = Operator
        fields  = '__all__'

kleemablech/admin/phone_number/forms.py
from django.forms import ModelForm

from kleemablech.models import PhoneNumber


class PhoneNumberForm(ModelForm):
    class Meta:
        model   = PhoneNumber
        fields  = '__all__'

kleemablech/admin/question/forms.py
from django.forms          import ModelForm

from suit_redactor.widgets import RedactorWidget

from kleemablech.models.faq import Question


class QuestionForm(ModelForm):
    class Meta:
        model   = Question
        fields  = '__all__'
        widgets = {
            'answer': RedactorWidget(editor_options={'lang': 'fr', 'minHeight': 300}),
        }

kleemablech/admin/refill/forms.py
from django.forms import ModelForm

from suit.widgets import SuitSplitDateTimeWidget

from kleemablech.models import Refill


class RefillForm(ModelForm):
    class Meta:
        model   = Refill
        fields  = '__all__'
        widgets = {
            'date': SuitSplitDateTimeWidget
        }

kleemablech/admin/share/forms.py
from django.forms import ModelForm
from django.forms import Textarea
from django.forms import TextInput
from django.forms import URLInput

from suit.widgets import SuitSplitDateTimeWidget

from kleemablech.models import FacebookShare
from kleemablech.models import UserFacebookShare


class FacebookShareForm(ModelForm):
    class Meta:
        model   = FacebookShare
        fields  = '__all__'
        widgets = {
            'name'   : TextInput(attrs={'class': 'input-xxlarge', }),
            'link'   : URLInput (attrs={'class': 'input-xxlarge', }),
            'message': Textarea (attrs={'class': 'input-xxlarge', 'rows': 3}),
            'caption': Textarea (attrs={'class': 'input-xxlarge', 'rows': 3}),
        }


class UserFacebookShareForm(ModelForm):
    class Meta:
        model   = UserFacebookShare
        fields  = '__all__'
        widgets = {
            'date': SuitSplitDateTimeWidget,
        }

kleemablech/templates/pages/contact.html
{% extends "base.html" %}

{% load i18n          %}
{% load static        %}
{% load recaptcha2    %}
{% load widget_tweaks %}

{% block title %}{% trans "Contact" %}{% endblock %}

{% block header_js %}
	{{ block.super }}
	{% recaptcha_init 'fr' %}
{% endblock %}

{% block content %}
	<div class="block-pagetitle">
		<div class="container">
			<h2>Contactez-nous</h2>
		</div>
	</div>

	<div class="contactpage">
		<div class="container">
			<div class="col-sm-8 col-sm-offset-2 connexion">
				<div class="row">
					<div class="title">
						<h2>Pour toutes vos questions ou demande d'informations</h2>
						<p>Veuillez remplir le formulaire ci-après.</p>
					</div>
					<form id="contact_form" role="form" action="{% url 'contact' %}" method="post" data-toggle="validator">
						{% csrf_token %}
						<div class="col-sm-6 col-xs-12 ">
							<div class="form-group">
								<label class="icon" for="name"><i class="fa fa-name"></i></label>
								{% render_field form.name class="form-control" placeholder="Nom & prénom" required="true"%}
								<div class="help-block with-errors"></div>
							</div>
						</div>
						<div class="col-sm-6 col-xs-12 ">
							<div class="form-group">
								<label class="icon" for="name"><i class="fa fa-envelope"></i></label>
								{% render_field form.email class="form-control" placeholder="E-mail" type="email" required="true"%}
								<div class="help-block with-errors"></div>
							</div>
						</div>
						<div class="clear"></div>
						<div class="innerdiv">
							<div class="form-group">
								<label class="icon " for="subject"><i class="fa fa-subject "></i></label>
								{% render_field form.subject class="form-control" required="true" %}
								<div class="help-block with-errors"></div>
							</div>
							<div class="form-group">
								<label class="icon mesge" for="date"><i class="fa fa-messages"></i></label>
								{% render_field form.message class="form-control" placeholder="Message" required="true" %}
								<div class="help-block with-errors"></div>
							</div>
						</div>
						<div class="clear"></div>
						<div class="col-sm-6 col-xs-12 ">
							<div class="captcha form-group">
								<div name="captcha"></div>
								{% render_field form.captcha required="true" %}
								<div class="help-block with-errors"></div>
							</div>
						</div>
						<div class="col-sm-6 col-xs-12 ">
							<div class="checked-option">
								<label >
									<input type="checkbox" value="2" required="true">
									J'ai lu et accepté les conditions générales d'utilisation du site Kleemablech.com
								</label>
							</div>
							<button class="btn btn-custum " type="submit">Envoyer mon message</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
	<div class='notifications center-bottom' align="center"></div>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'js/contact.js' %}"></script>
{% endblock %}

kleemablech/templates/pages/parameters.html
{% extends "pages/profile_base.html" %}

{% load i18n          %}
{% load static        %}
{% load cropping      %}
{% load widget_tweaks %}

{% block content %}
	{% with 'parameters' as current_tab %}
	{{block.super}}
	{% endwith %}
{% endblock content %}

{% block title %}{% trans "Parametres" %}{% endblock %}

{% block css %}
{{block.super}}
<style>
	.file-upload {
		display: none;
	}
	#cropping_form > :not(.jcrop-image) {
		display: none;
	}
	.jcrop-image {
		margin: auto;
	}
</style>
{% endblock %}

{% block profile_tab %}
<div class="modal fade" role="dialog" id="cropping_modal" style="top: calc(50% - 200px) !important;">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" >Image de profil</h4>
			</div>
			<div class="modal-body"></div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary">Enregistrer</button>
			</div>
		</div>
	</div>
</div>

<section class="dashboardpage">
	<div class="container">
		<div class="row">
			<div class="block-separe">
				<h4> Bonjour {{ user.username }} </h4>
				<span class="subtitle">Vous pouvez gérer vos informations personnelles</span>
				<a href="#" class="modifier" id="update_parameters">modifier</a>
			</div>

			<div class="block-parametre" id="read_only_parameters">
				<div class="boxprametre">
					<div class="col-sm-4 col-xs-12">
						<div class="imageUpload">
							<img id="profile-pic" class="profile-pic" src="{% cropped_thumbnail user 'cropping' %}" width="255" height="255">
							{% render_field form.picture class+="file-upload" style="display: none;" %}
						</div>
					</div>
					<div class="col-sm-8 col-xs-12 parmeteruser">
						<ul>
							<li> <i class="fa fa-gender"></i> <span>{{ form.gender.value }}</span> </li>
							<li> <i class="fa fa-name"></i> <span>{{ form.first_name.value }}</span> </li>
							<li> <i class="fa fa-lock "></i> <span> *******************</span> </li>
							<li> <i class="fa fa-date"></i> <span>{{ form.birthday.value }}</span> </li>
							<li> <i class="fa fa-envelope"></i> <span>{{ form.email.value }}</span> </li>
							<li> <i class="fa fa-name"></i> <span>{{ form.last_name.value }}</span> </li>
							<li> <i class="fa fa-region"></i> <span>{{ form.region.value }}</span> </li>
							<li> <i class="fa fa-phones"></i> <span class="geofont">{{ user.phonenumber_set.first }}</span>
						</ul>
					</div>
				</div>
			</div>

			<div class="block-parametre" id="updatable_parameters" style="display:none">
				<div class="row">
					<form id="user_parameters_form" role="form" action="{% url 'parameters' %}" method="POST" data-toggle="validator">
						{% csrf_token %}
						<div class="boxprametre">
							<div class="col-sm-4 col-xs-12">
								<div class="imageUpload">
									<img id="profile-pic" class="profile-pic" src="{% cropped_thumbnail user 'cropping' %}" width="255" height="255">
									<a class="addPhotos" href="#">+</a>
									{% render_field form.picture class+="file-upload" style="display: none;" %}
								</div>
							</div>

							<div class="col-sm-4 col-xs-12">
								<div class="form-group">
									<label class="icon" for="gender">
										<i class="fa fa-gender"></i>
									</label>
									{% render_field form.gender class="form-control no-combo-select" required="true" %}
									<div class="help-block with-errors"></div>
								</div>
							</div>

							<div class="col-sm-4 col-xs-12">
								<div class="form-group">
									<label class="icon" for="first_name">
										<i class="fa fa-name"></i>
									</label>
									{% render_field form.first_name class="form-control" placeholder="prenom" required="true" %}
									<div class="help-block with-errors"></div>
								</div>
							</div>

							<div class="col-sm-4 col-xs-12">
								<div class="form-group">
									<label class="icon" for="password">
										<i class="fa fa-lock"></i>
									</label>
									{% render_field form.password class="form-control" placeholder="••••••••••••" %}
									<div class="help-block with-errors"></div>
								</div>
							</div>

							<div class="col-sm-4 col-xs-12">
								<div class="form-group">
									<label class="icon" for="birthday">
										<i class="fa fa-date"></i>
									</label>
									{% render_field form.birthday class="form-control" placeholder="date de naissance" required="true" data-provide="datepicker" data-date-format="dd/mm/yyyy" data-date-language="fr" %}
									<div class="help-block with-errors"></div>
								</div>
							</div>

							<div class="col-sm-4 col-xs-12">
								<div class="form-group">
									<label class="icon" for="email">
										<i class="fa fa-envelope"></i>
									</label>
									{% render_field form.email type="email" class="form-control" required="true" %}
									<div class="help-block with-errors"></div>
								</div>
							</div>

							<div class="col-sm-4 col-xs-12">
								<div class="form-group">
									<label class="icon" for="last_name">
										<i class="fa fa-name"></i>
									</label>
									{% render_field form.last_name class="form-control" placeholder="nom" required="true" %}
									<div class="help-block with-errors"></div>
								</div>
							</div>

							<div class="col-sm-4 col-xs-12">
								<div class="form-group">
									<label class="icon" for="region">
										<i class="fa fa-region"></i>
									</label>
									{% render_field form.region class="form-control no-combo-select" class="form-control" required="true" %}
									<div class="help-block with-errors"></div>
								</div>
							</div>

							<div class="col-sm-4 col-xs-12">
								<div class="form-group">
									<label class="icon" for="region">
										<i class="fa fa-phones"></i>
									</label>
									<select id="phone_numbers_list" class="form-control no-combo-select" id="phones" name="phones" required="true">
										{% for phone_number in user.phonenumber_set.all %}
										<option>{{ phone_number.number }}</option>
										{% endfor %}
									</select>
								</div>
							</div>
						</div>
						<button class="btn btn-custum pull-right" type="submit">Enregistrer</button>
						<a class="btn btn-custum pull-right" data-toggle="modal" data-target="#edit_phones">Ajouter un numéro</a>
					</form>
				</div>
			</div>
		</div>
	</div>
</section>

<div id="edit_phones" class="modal fade" role="dialog" style="top: calc(50% - 200px) !important;">
	<div class="modal-dialog">
		<div class="modal-content">
			<form id="new_phone_form" data-async data-target="#edit-phones"
				  method="post" action="{% url 'phone_numbers' %}" data-toggle="validator">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Ajouter un numèro de téléphone</h4>
				</div>
				<div class="modal-body">
					{% csrf_token %}
					<div class="form-group has-feedback">
						<label class="control-label" for="number"></label>
						<input class="form-control" id="number" name="number" type="text" required="true">
						<i class="glyphicon glyphicon-phone form-control-feedback"></i>
						<div class="help-block with-errors"></div>
					</div>
				</div>
				<div class="modal-footer">
					<button type="submit" class="btn btn-primary">Ajouter</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Annuler</button>
				</div>
			</form>
		</div>
	</div>
</div>
<div class='notifications center-bottom' align="center"></div>
{% endblock %}

{% block extra_js %}
{{ form.media }}
	<script src="{% static 'js/parameters.js' %}"></script>
	<script>
		var picture_upload_url = "{% url 'picture_upload' %}";
	</script>
{% endblock %}

kleemablech/templates/pages/transfert.html
{% extends "pages/profile_base.html" %}

{% load i18n          %}
{% load static        %}
{% load widget_tweaks %}

{% block content %}
	{% with 'transfert' as current_tab %}
		{{block.super}}
	{% endwith %}
{% endblock content %}

{% block title %}{% trans "Transfert" %}{% endblock title %}

{% block css %}
	{{block.super}}
	<link rel="stylesheet" href="{% static 'css/bootstrap-notify.css'%}">
{% endblock %}

{% block profile_tab %}
<section class="dashboardpage">
	<div class="container">
		<div class="row">
			<div class="top-transfert">
				<div class="boxCredit">
					Votre solde est
					<span class="creditNum">
						{{ credit_dinars }}<sup>dt</sup>
						<span>{{ credit_millimes }}</span>
					</span>
				</div>
				<p>
					Vous pouvez choisir le montant à transférer, le montant doit être supérieur ou égale à 1 dinar.
					<br>
					Le transfert prendra 24h pour être effectué.
				</p>
			</div>
			<div class="col-md-offset-4 col-sm-offset-1 col-md-4 col-sm-10 col-xs-12 connexion">
				<div class="row">
					<div class="title">
						<p>Veuillez choisir le numéro et le montant à transférer</p>
					</div>
					<div class="phone-slide">
						<ul class="slides">
							{% for phone in user.phonenumber_set.all %}
								<li>
									<div class="logo-or">
										{% if phone.operator == "ooredoo" %}
											<img src="{% static 'images/ooredoo.png' %}">
										{% elif phone.operator == "orange" %}
											<img src="{% static 'images/orange.png' %}">
										{% elif phone.operator == "tunisie_telecom" %}
											<img src="{% static 'images/tunisie_telecom.png' %}">
										{% endif %}
									</div>
									<div class="numchrge">{{ phone.number }}</div>
								</li>
							{% endfor %}
						</ul>
					</div>
					<form role="form" id="transfert_form" action="{% url 'transfert' %}" method="post" data-toggle="validator">
						{% csrf_token %}
						{{ form.number }}
						<div class="col-sm-12 col-xs-12 socialbox">
							<div class="form-group">
								<label class="icon" for="montant">
									<i class="fa fa-montant"></i>
								</label>
								{% blocktrans asvar error_msg %}
									Please select a numerical value between 1 and {{total_credit}}
								{% endblocktrans %}
								{% render_field form.amount placeholder="Montant à recharger" class="form-control" required="true" type="number" min="1" max=total_credit data-error=error_msg %}
								<div class="help-block with-errors"></div>
							</div>
							<button class="btn btn-custum " type="submit">Valider</button>
						</div>
					</form>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
</section>
<div class="clearfix"></div>
<div class='notifications center-bottom' align="center"></div>
{% endblock %}

{% block extra_js %}
	<script src="{% static 'js/transfert.js' %}"></script>
{% endblock %}